In [5]:
import pandas as pd
import numpy as np

In [7]:
data=pd.read_excel("Lab Session Data.xlsx", sheet_name="Purchase data")


In [ ]:
data.head(10)


Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)  \
0      C_1           20             6                 2           386   
1      C_2           16             3                 6           289   
2      C_3           27             6                 2           393   
3      C_4           19             1                 2           110   
4      C_5           24             4                 2           280   
5      C_6           22             1                 5           167   
6      C_7           15             4                 2           271   
7      C_8           18             4                 2           274   
8      C_9           21             1                 4           148   
9     C_10           16             2                 4           198   

   Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  ...  \
0         NaN         NaN         NaN         NaN         NaN  ...   
1         NaN         NaN         NaN         NaN         NaN  ...   
2         NaN         NaN         NaN         NaN         NaN  ...   
3         NaN         NaN         NaN         NaN         NaN  ...   
4         NaN         NaN         NaN         NaN         NaN  ...   
5         NaN         NaN         NaN         NaN         NaN  ...   
6         NaN         NaN         NaN         NaN         NaN  ...   
7         NaN         NaN         NaN         NaN         NaN  ...   
8         NaN         NaN         NaN         NaN         NaN  ...   
9         NaN         NaN         NaN         NaN         NaN  ...   

   Unnamed: 12  Unnamed: 13  Unnamed: 14  Unnamed: 15  Unnamed: 16  \
0          NaN          NaN          NaN          NaN          NaN   
1          NaN          NaN          NaN          NaN          NaN   
2          NaN          NaN          NaN          NaN          NaN   
3          NaN          NaN          NaN          NaN          NaN   
4          NaN          NaN          NaN          NaN          NaN   
5          NaN          NaN          NaN          NaN          NaN   
6          NaN          NaN          NaN          NaN          NaN   
7          NaN          NaN          NaN          NaN          NaN   
8          NaN          NaN          NaN          NaN          NaN   
9          NaN          NaN          NaN          NaN          NaN   

   Unnamed: 17  Unnamed: 18  Candy  Mango  Milk  
0          NaN          NaN    1.0   55.0  18.0  
1          NaN          NaN    NaN    NaN   NaN  
2          NaN          NaN    NaN    NaN   NaN  
3          NaN          NaN    NaN    NaN   NaN  
4          NaN          NaN    NaN    NaN   NaN  
5          NaN          NaN    NaN    NaN   NaN  
6          NaN          NaN    NaN    NaN   NaN  
7          NaN          NaN    NaN    NaN   NaN  
8          NaN          NaN    NaN    NaN   NaN  
9          NaN          NaN    NaN    NaN   NaN  

[10 rows x 22 columns]

In [12]:
# Feature matrix X
X = data[["Candies (#)", "Mangoes (Kg)", "Milk Packets (#)"]].values

# Output vector y
y = data["Payment (Rs)"].values

X, y


(array([[20,  6,  2],
        [16,  3,  6],
        [27,  6,  2],
        [19,  1,  2],
        [24,  4,  2],
        [22,  1,  5],
        [15,  4,  2],
        [18,  4,  2],
        [21,  1,  4],
        [16,  2,  4]]),
 array([386, 289, 393, 110, 280, 167, 271, 274, 148, 198]))

In [15]:
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)


Shape of X: (10, 3)
Shape of y: (10,)


In [17]:
rank_X = np.linalg.matrix_rank(X)
rank_X


np.int64(3)

In [20]:
def pinv(X):
 X_pinv = np.linalg.pinv(X)
 cost = X_pinv @ y
 return cost

c=pinv(X)
c

array([ 1., 55., 18.])

In [6]:
#4th question

df=pd.read_excel("Lab Session Data.xlsx", sheet_name="thyroid0387_UCI")



In [7]:
df.head()

Record ID  age sex on thyroxine query on thyroxine  \
0  840801013   29   F            f                  f   
1  840801014   29   F            f                  f   
2  840801042   41   F            f                  f   
3  840803046   36   F            f                  f   
4  840803047   32   F            f                  f   

  on antithyroid medication sick pregnant thyroid surgery I131 treatment  ...  \
0                         f    f        f               f              f  ...   
1                         f    f        f               f              f  ...   
2                         f    f        f               f              f  ...   
3                         f    f        f               f              f  ...   
4                         f    f        f               f              f  ...   

  TT4 measured  TT4 T4U measured T4U FTI measured FTI TBG measured TBG  \
0            f    ?            f   ?            f   ?            f   ?   
1            t  128            f   ?            f   ?            f   ?   
2            f    ?            f   ?            f   ?            t  11   
3            f    ?            f   ?            f   ?            t  26   
4            f    ?            f   ?            f   ?            t  36   

  referral source     Condition  
0           other  NO CONDITION  
1           other  NO CONDITION  
2           other  NO CONDITION  
3           other  NO CONDITION  
4           other             S  

[5 rows x 31 columns]

In [8]:
age=df[["age"]]
age

age
0      29
1      29
2      41
3      36
4      32
...   ...
9167   56
9168   22
9169   69
9170   47
9171   31

[9172 rows x 1 columns]

In [9]:
def mean_b(X):
 return np.mean(X)

agee=mean_b(age)
print(agee)

73.55582206716092


In [10]:
def var_b(X):
 return np.var(X)

var_age=var_b(age)
print(var_age)

age    1.401648e+06
dtype: float64


d:\Anakonda\Lib\site-packages\numpy\_core\fromnumeric.py:4316: FutureWarning: The behavior of DataFrame.var with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return var(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)


In [12]:

df=df[["TSH"]].replace("?",0)
df[["TSH"]]

TSH
0     0.3
1     1.6
2     0.0
3     0.0
4     0.0
...   ...
9167  0.0
9168  0.0
9169  0.0
9170  0.0
9171  0.0

[9172 rows x 1 columns]

In [16]:
#? to 0
#0 to median
df=df[["TSH"]].replace("0",np.median)
df[["TSH"]]


TSH
0     0.3
1     1.6
2     0.0
3     0.0
4     0.0
...   ...
9167  0.0
9168  0.0
9169  0.0
9170  0.0
9171  0.0

[9172 rows x 1 columns]

In [ ]:
# ML Lab 1 — Clean VS Code Version

import pandas as pd
import numpy as np
import time
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics.pairwise import cosine_similarity
# Update this path to where your Excel file exists locally
file_path = r"D:\ML_LAB\ml_lab_data.xlsx"  # <-- CHANGE THIS

def mean_manual(data):
    return sum(data) / len(data)


def variance_manual(data):
    m = mean_manual(data)
    return sum((x - m) ** 2 for x in data) / len(data)


def jaccard_smc(v1, v2):
    f11 = np.sum((v1 == 1) & (v2 == 1))
    f00 = np.sum((v1 == 0) & (v2 == 0))
    f01 = np.sum((v1 == 0) & (v2 == 1))
    f10 = np.sum((v1 == 1) & (v2 == 0))

    jc = f11 / (f01 + f10 + f11) if (f01 + f10 + f11) else 0
    smc = (f11 + f00) / (f11 + f00 + f01 + f10)
    return jc, smc

purchase_df = pd.read_excel(file_path, sheet_name="Purchase data")

X = purchase_df[["Candies (#)", "Mangoes (Kg)", "Milk Packets (#)"]].values
y = purchase_df["Payment (Rs)"].values

rank = np.linalg.matrix_rank(X)
model = np.linalg.pinv(X) @ y

print("Rank:", rank)
print("Costs → Candies, Mangoes, Milk:", model)

purchase_df["Status"] = purchase_df["Payment (Rs)"].apply(lambda x: "RICH" if x > 200 else "POOR")

le = LabelEncoder()
y_encoded = le.fit_transform(purchase_df["Status"])

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X, y_encoded)

print("Predictions:", le.inverse_transform(knn.predict(X[:5])))

## 6️⃣ A3: IRCTC Stock Analysis

irctc_df = pd.read_excel(file_path, sheet_name="IRCTC Stock Price")
prices = irctc_df["Price"].dropna().values

print("Mean (Manual):", mean_manual(prices))
print("Mean (NumPy):", np.mean(prices))

loss_prob = len(irctc_df[irctc_df["Chg%"] < 0]) / len(irctc_df)
print("Loss Probability:", loss_prob)

plt.figure(figsize=(7,4))
sns.scatterplot(x="Day", y="Chg%", data=irctc_df)
plt.show()


## 7️ A4–A9: Thyroid Dataset Processing

thyroid_df = pd.read_excel(file_path, sheet_name="thyroid0387_UCI")

numeric_cols = ['age','TSH','T3','TT4','T4U','FTI','TBG']
for col in numeric_cols:
    thyroid_df[col] = pd.to_numeric(thyroid_df[col].replace('?', np.nan))

for col in numeric_cols:
    thyroid_df[col].fillna(thyroid_df[col].median(), inplace=True)

binary_cols = ['on thyroxine','query on thyroxine','sick','pregnant','thyroid surgery']
binary_df = thyroid_df[binary_cols].applymap(lambda x: 1 if x == 't' else 0)

jc, smc = jaccard_smc(binary_df.iloc[0].values, binary_df.iloc[1].values)
print("Jaccard:", jc, "SMC:", smc)

v1 = thyroid_df[numeric_cols].iloc[0].values.reshape(1,-1)
v2 = thyroid_df[numeric_cols].iloc[1].values.reshape(1,-1)

print("Cosine Similarity:", cosine_similarity(v1, v2)[0][0])

sim_matrix = cosine_similarity(binary_df.head(20))
sns.heatmap(sim_matrix, cmap="YlGnBu")
plt.show()

scaler = MinMaxScaler()
thyroid_df[numeric_cols] = scaler.fit_transform(thyroid_df[numeric_cols])
print(thyroid_df.head())


